# Generated by Django 3.0.14 on 2023-07-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=30)),
                ('kategori', models.CharField(choices=[('Cat', 'Cat'), ('Semen', 'Semen'), ('Gypsum', 'Gypsum')], default='Semen', max_length=10)),
                ('harga_beli', models.IntegerField(max_length=20)),
                ('harga_jual', models.IntegerField(max_length=20)),
            ],
        ),
    ]
